<?php

return [

    'cta_url' => env('SALES_CTA_URL', '#pricing'),

    'tool_logos' => [
        'Nano Banana', 'Grok', 'Seedance', 'Kling', 'Veo', 'HeyGen',
        'ElevenLabs', 'Suno', 'Ideogram', 'Midjourney', 'Runway', 'Flux',
    ],

    'categories' => [
        [
            'id' => 'image',
            'title' => 'AI Image Tools',
            'subtitle' => 'Generate, edit, and scale visual content in seconds.',
            'icon' => 'image',
            'gradient' => 'from-violet-500/20 via-fuchsia-500/10 to-transparent',
            'use_cases' => [
                ['label' => 'AI Clones'],
                ['label' => 'Social Media Posts'],
                ['label' => 'Graphic Design'],
                ['label' => 'Image Editing'],
                ['label' => 'YouTube Thumbnails'],
                ['label' => 'Online Ads'],
            ],
        ],
        [
            'id' => 'video',
            'title' => 'AI Video Tools',
            'subtitle' => 'Cinematic clips, ads, and short-form — without a studio.',
            'icon' => 'video',
            'gradient' => 'from-cyan-500/20 via-blue-500/10 to-transparent',
            'use_cases' => [
                ['label' => 'Clone Videos'],
                ['label' => 'Visual Effects'],
                ['label' => 'Cinematic Films'],
                ['label' => 'Video Ads'],
                ['label' => 'Reels & TikToks'],
                ['label' => 'YouTube Videos'],
            ],
        ],
        [
            'id' => 'audio',
            'title' => 'AI Audio Tools',
            'subtitle' => 'Voice, music, and sound design — royalty-ready.',
            'icon' => 'audio',
            'gradient' => 'from-amber-500/20 via-orange-500/10 to-transparent',
            'use_cases' => [
                ['label' => 'AI Voiceovers'],
                ['label' => 'AI Voice Clones'],
                ['label' => 'Voice Swaps'],
                ['label' => 'AI Sound Effects'],
                ['label' => 'AI Music Generation'],
            ],
        ],
        [
            'id' => 'plugins',
            'title' => 'AI Editing Plugins',
            'subtitle' => 'Generate inside Premiere, DaVinci, Final Cut & more.',
            'icon' => 'plugins',
            'gradient' => 'from-emerald-500/20 via-teal-500/10 to-transparent',
            'use_cases' => [
                ['label' => 'In-app AI generation'],
                ['label' => 'Instant project import'],
                ['label' => 'No browser switching'],
            ],
        ],
    ],

    'plans' => [
        [
            'id' => 'credits',
            'name' => 'Student Credit Pack',
            'price' => '$98',
            'period' => 'one-time',
            'credits' => '$110 worth of AI credits',
            'badge' => 'Save 10%',
            'highlighted' => false,
            'features' => [
                'Use credits on any tool across the marketplace',
                'No subscription required — pay as you go',
                'Nano Banana, Grok, Kling, Veo, HeyGen & more',
                'Top up anytime when you run out',
            ],
            'cta' => 'Claim credit offer',
        ],
        [
            'id' => 'subscription',
            'name' => 'Creator Pro',
            'price' => '$39',
            'period' => '/month',
            'credits' => '$49 in credits every month',
            'badge' => 'Best value',
            'highlighted' => true,
            'features' => [
                '20% boost on monthly credits + 10% off top-ups',
                'Unlimited Content Creator Templates Library',
                '100,000+ LUTs, SFX, titles, overlays & backgrounds',
                'Faster generations & parallel runs',
                'Cancel anytime',
            ],
            'cta' => 'Start creating',
        ],
    ],

    'template_categories' => [
        [
            'id' => 'luts',
            'title' => 'Color Grading LUTs',
            'count' => '4,000+',
            'description' => 'Cinematic color presets that work in any editor. Drag, drop, done.',
            'emoji' => '🎨',
        ],
        [
            'id' => 'sfx',
            'title' => 'Sound Effects',
            'count' => '60,000+',
            'description' => 'Professionally made SFX with powerful search and categories.',
            'emoji' => '🎧',
        ],
        [
            'id' => 'text',
            'title' => 'Text & Titles',
            'count' => '3,000+',
            'description' => 'Scroll-stopping typography templates for every major NLE.',
            'emoji' => '💬',
        ],
        [
            'id' => 'overlays',
            'title' => 'Overlays & Textures',
            'count' => '2,000+',
            'description' => 'Viral-ready textures and vintage vibes in seconds.',
            'emoji' => '✨',
        ],
        [
            'id' => 'backgrounds',
            'title' => 'Animated Backgrounds',
            'count' => '5,000+',
            'description' => 'Clean, modern bases for text, graphics, and motion.',
            'emoji' => '🖼️',
        ],
    ],

    'template_gallery' => [
        [
            'id' => 'cinematic-lut',
            'title' => 'Cinematic Teal & Orange',
            'categoryId' => 'luts',
            'categoryLabel' => 'LUT',
            'preview' => 'lut',
            'size' => 'wide',
            'accent' => 'from-orange-500/40 via-teal-600/50 to-slate-900',
        ],
        [
            'id' => 'moody-grade',
            'title' => 'Moody Film Grade',
            'categoryId' => 'luts',
            'categoryLabel' => 'LUT',
            'preview' => 'lut',
            'size' => 'default',
            'accent' => 'from-indigo-900 via-purple-900 to-black',
        ],
        [
            'id' => 'whoosh-pack',
            'title' => 'Cinematic Whoosh Pack',
            'categoryId' => 'sfx',
            'categoryLabel' => 'SFX',
            'preview' => 'sfx',
            'size' => 'tall',
            'accent' => 'from-violet-600/30 via-[#13131f] to-cyan-600/20',
        ],
        [
            'id' => 'impact-hit',
            'title' => 'Trailer Impact Hit',
            'categoryId' => 'sfx',
            'categoryLabel' => 'SFX',
            'preview' => 'sfx',
            'size' => 'default',
            'accent' => 'from-amber-500/25 via-[#13131f] to-red-900/30',
        ],
        [
            'id' => 'kinetic-title',
            'title' => 'Kinetic Bold Title',
            'categoryId' => 'text',
            'categoryLabel' => 'Text',
            'preview' => 'text',
            'size' => 'wide',
            'accent' => 'from-fuchsia-600/30 via-violet-900/50 to-black',
        ],
        [
            'id' => 'lower-third',
            'title' => 'Minimal Lower Third',
            'categoryId' => 'text',
            'categoryLabel' => 'Text',
            'preview' => 'text',
            'size' => 'default',
            'accent' => 'from-slate-800 via-slate-900 to-black',
        ],
        [
            'id' => 'film-grain',
            'title' => '35mm Film Grain',
            'categoryId' => 'overlays',
            'categoryLabel' => 'Overlay',
            'preview' => 'overlay',
            'size' => 'default',
            'accent' => 'from-stone-600/40 via-neutral-900 to-black',
        ],
        [
            'id' => 'light-leaks',
            'title' => 'Warm Light Leaks',
            'categoryId' => 'overlays',
            'categoryLabel' => 'Overlay',
            'preview' => 'overlay',
            'size' => 'tall',
            'accent' => 'from-amber-400/35 via-rose-500/20 to-transparent',
        ],
        [
            'id' => 'vhs-retro',
            'title' => 'VHS Retro Texture',
            'categoryId' => 'overlays',
            'categoryLabel' => 'Overlay',
            'preview' => 'overlay',
            'size' => 'default',
            'accent' => 'from-pink-500/20 via-purple-900/40 to-blue-900/30',
        ],
        [
            'id' => 'gradient-loop',
            'title' => 'Soft Gradient Loop',
            'categoryId' => 'backgrounds',
            'categoryLabel' => 'Background',
            'preview' => 'background',
            'size' => 'wide',
            'accent' => 'from-violet-500/50 via-fuchsia-500/30 to-cyan-500/40',
        ],
        [
            'id' => 'abstract-motion',
            'title' => 'Abstract Motion Shapes',
            'categoryId' => 'backgrounds',
            'categoryLabel' => 'Background',
            'preview' => 'background',
            'size' => 'default',
            'accent' => 'from-cyan-500/30 via-blue-900/50 to-indigo-950',
        ],
        [
            'id' => 'podcast-lut',
            'title' => 'Clean Podcast Look',
            'categoryId' => 'luts',
            'categoryLabel' => 'LUT',
            'preview' => 'lut',
            'size' => 'default',
            'accent' => 'from-emerald-600/30 via-slate-800 to-slate-950',
        ],
    ],

    'testimonials' => [
        [
            'quote' => 'We got more editing work done in 3 hours than we normally do in 3 days!',
            'author' => 'Hilda Schlueter',
            'role' => 'Online Course Creator',
        ],
        [
            'quote' => "My videos wouldn't look HALF as good without the Templates Library.",
            'author' => 'Matt Lilley',
            'role' => 'Content Creator Student',
        ],
        [
            'quote' => "I don't need any other digital asset subscriptions.",
            'author' => 'Brady Hales',
            'role' => 'Content Creator Student',
        ],
    ],

    'faqs' => [
        [
            'question' => 'What is Prompt Edit?',
            'answer' => 'Think of Prompt Edit as a grocery store for AI tools. Access every major creator AI in one place — no stacking subscriptions. Buy credits, use what you need, and only pay for what you actually create.',
        ],
        [
            'question' => 'Can I use creations commercially?',
            'answer' => 'Yes. Everything you create or download during an active membership is cleared for commercial use. One fee covers licensing — no surprise upsells.',
        ],
        [
            'question' => 'Is quality different from the original tool sites?',
            'answer' => 'No quality difference. You access the same models on a pay-per-use basis instead of locking into individual monthly plans.',
        ],
        [
            'question' => 'What is the Content Creator Templates Library?',
            'answer' => '100,000+ royalty-free editing assets: LUTs, SFX, titles, overlays, backgrounds, presets, and more. Included unlimited with Creator Pro.',
        ],
        [
            'question' => 'Are downloads limited?',
            'answer' => 'Unlimited downloads for your account. Per our terms: individual use only, no account sharing or automated scraping.',
        ],
        [
            'question' => 'Can I cancel anytime?',
            'answer' => 'Absolutely. Cancel through the site or email support. Within 30 days of signup, unused credits are refundable per our guarantee.',
        ],
    ],

];
